# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# SDK Configuration
SDK_VERSION_NAME=1.2.42
SDK_VERSION_CODE=50
SDK_MIN_SDK_VERSION=24
SDK_TARGET_SDK_VERSION=34
SDK_COMPILE_SDK_VERSION=34

# Publishing Configuration
PUBLISH_GROUP_ID=com.artiusid
PUBLISH_ARTIFACT_ID=artiusid-sdk
PUBLISH_VERSION=1.2.42
android.useAndroidX=true
android.enableJetifier=true
